export const CARREGAR_DESPESAS = 'CARREGAR_DESPESAS'
export const CARREGAR_POUPANCAS = 'CARREGAR_POUPANCAS'
export const CARREGAR_PRODUTOS = 'CARREGAR_PRODUTOS'
export const CARREGAR_TAREFAS = 'CARREGAR_TAREFAS'
